// Liste des informations sur la physique et autres informations
const infos = [
  "La physique est la branche de la science qui étudie la nature fondamentale de l’univers.",
  "La théorie de la relativité restreinte d’Einstein a révolutionné la compréhension de l’espace, du temps et de l’énergie.",
  "La mécanique quantique décrit le comportement des particules subatomiques à l’échelle quantique.",
  "Les quatre forces fondamentales de la physique sont la gravité, l’électromagnétisme, la force nucléaire forte et la force nucléaire faible.",
  "Les particules élémentaires, telles que les quarks et les leptons, sont les constituants de base de la matière.",
  "Le boson de Higgs, découvert en 2012, explique comment les particules acquièrent leur masse.",
  "La constante de Planck, h, est fondamentale en physique quantique et définit la taille des quanta d’énergie.",
  "La lumière peut se comporter à la fois comme une particule (le photon) et une onde, un phénomène appelé dualité onde-particule.",
  "La thermodynamique étudie les transferts d’énergie, les processus thermiques et les systèmes en équilibre thermique.",
  "La loi de la conservation de l’énergie stipule que l’énergie totale d’un système isolé reste constante.",
  "Les lois de Kepler décrivent les mouvements des planètes autour du Soleil, formant la base de la mécanique céleste.",
  "La loi de la gravitation universelle d’Isaac Newton explique comment les objets s’attirent mutuellement en raison de leur masse.",
  "L’équation E=mc^2 exprime la relation entre l’énergie € et la masse (m) d’un objet, indiquant la convertibilité entre les deux.",
  "Les ondes électromagnétiques, telles que la lumière visible, se propagent à une vitesse constante dans le vide, soit environ 299 792 458 m/s.",
  "La mécanique classique d’Newton est efficace pour décrire les mouvements à des vitesses bien inférieures à celle de la lumière.",
  "Les particules quantiques peuvent être intriquées, où l’état d’une particule est directement lié à l’état d’une autre, même à des distances considérables.",
  "La physique des particules explore les composants subatomiques de la matière et les interactions fondamentales.",
  "Les trous noirs sont des régions de l’espace où la gravité est si intense que rien, même la lumière, ne peut s’échapper.",
  "La dualité onde-corpuscule de la matière a été établie par l’expérience de la diffusion des électrons de Davisson et Germer.",
  "Les supercordes sont des entités théoriques qui pourraient expliquer la nature fondamentale des particules subatomiques.",
  "Les lois de la thermodynamique incluent la conservation de l’énergie, l’augmentation de l’entropie et l’impossibilité d’atteindre le zéro absolu.",
  "L’effet photoélectrique, étudié par Albert Einstein, a contribué à la compréhension de la nature quantique de la lumière.",
  "La radioactivité, découverte par Henri Becquerel, a révolutionné la compréhension des transformations nucléaires.",
  "La physique nucléaire examine les propriétés et les interactions des noyaux atomiques.",
  "Les accélérateurs de particules, tels que le LHC au CERN, permettent d’étudier des énergies et des processus inaccessibles autrement.",
  "Les cellules souches ont le potentiel de se différencier en différents types de cellules spécialisées.",
  "L’ADN, découvert en 1953 par James Watson et Francis Crick, est la molécule porteuse de l’information génétique.",
  "La bioluminescence est la production de lumière par des organismes vivants, comme les lucioles ou certaines méduses.",
  "L’effet de serre est essentiel pour maintenir la température de la Terre, mais les activités humaines ont intensifié cet effet.",
  "Les protéines sont des macromolécules constituées d’acides aminés, jouant un rôle clé dans de nombreuses fonctions biologiques.",
  "Les pulsars sont des étoiles à neutrons tournant rapidement, émettant des faisceaux de radiations à intervalles réguliers.",
  "Les gènes Hox jouent un rôle crucial dans le développement embryonnaire, régulant la mise en place des axes du corps.",
  "L’effet Doppler est observé lorsque la fréquence d’une onde varie en fonction du mouvement relatif de la source et de l’observateur.",
  "La photosynthèse est le processus par lequel les plantes convertissent la lumière solaire en énergie chimique.",
  "Les supernovas sont d’énormes explosions d’étoiles, libérant des éléments lourds dans l’espace.",
  "L’épigénétique étudie les changements dans l’expression des gènes sans altération de la séquence ADN.",
  "La matière noire, invisible mais exerçant une force gravitationnelle, représente une grande partie de la masse de l’univers.",
  "Les mémoires à long terme sont stockées dans le cerveau sous forme de connexions synaptiques renforcées.",
  "Les nanomatériaux, à l’échelle nanométrique, présentent des propriétés uniques utilisées dans divers domaines, tels que la nanotechnologie.",
  "L’électroencéphalogramme (EEG) enregistre l’activité électrique du cerveau, permettant d’étudier les ondes cérébrales.",
  "La loi de Moore prédit que la puissance des ordinateurs double environ tous les deux ans.",
  "Les arcs-en-ciel résultent de la dispersion de la lumière dans les gouttes d’eau atmosphériques.",
  "Les virus sont des entités biologiques qui nécessitent des cellules hôtes pour se reproduire.",
  "La tectonique des plaques explique la dérive des continents et la formation des montagnes.",
  "L’énergie noire est une force mystérieuse qui semble accélérer l’expansion de l’univers.",
  "Les antibiotiques sont des substances chimiques utilisées pour combattre les infections bactériennes.",
  "L’effet placebo démontre que l’amélioration des symptômes peut parfois résulter de l’attente psychologique plutôt que du traitement réel.",
  "La cryogénie est l’étude des températures extrêmement basses, souvent utilisée pour conserver des échantillons biologiques.",
  "Les réactions chimiques dans le corps sont régulées par des enzymes, accélérant les processus biologiques.",
  "La théorie de l’évolution de Darwin propose que les espèces évoluent au fil du temps par le biais de la sélection naturelle.",
  "La chimie organique étudie les composés à base de carbone, tandis que la chimie inorganique se concentre sur les composés sans carbone.",
  "La molécule d'eau (H2O) est essentielle à la vie et est un composé chimique courant étudié en chimie.",
  "La réaction de combustion du méthane (CH4) produit du dioxyde de carbone (CO2) et de l'eau (H2O).",
  "Les catalyseurs sont des substances qui accélèrent les réactions chimiques sans être consommés dans le processus.",
  "La chromatographie est une technique de séparation des composés chimiques en fonction de leur affinité pour une phase stationnaire.",
  "Les isotopes sont des atomes d'un élément qui ont le même nombre de protons mais un nombre différent de neutrons.",
  "La spectroscopie utilise le spectre électromagnétique pour étudier la structure des molécules et des atomes.",
  "Les acides aminés sont les éléments constitutifs des protéines et sont étudiés en biochimie.",
  "La loi de la conservation de la masse stipule que la masse totale des réactifs est égale à la masse totale des produits dans une réaction chimique.",
  "La polymérisation est le processus de formation de polymères à partir de monomères.",
  "Les électrons de valence sont les électrons situés dans la couche électronique la plus externe d'un atome et sont responsables des liaisons chimiques.",
  "La théorie cinétique des gaz décrit le comportement des gaz en termes de mouvement des particules.",
  "La catalyse enzymatique est un processus biologique dans lequel les enzymes accélèrent les réactions chimiques dans les organismes vivants.",
  "La structure de l'ADN (acide désoxyribonucléique) a été découverte par James Watson et Francis Crick en 1953.",
  "La concentration molaire mesure la quantité de substance dissoute dans une solution par unité de volume.",
  "Les réactions d'oxydation impliquent la perte d'électrons, tandis que les réactions de réduction impliquent le gain d'électrons.",
  "La loi d'Avogadro stipule que des volumes égaux de gaz, dans les mêmes conditions de température et de pression, contiennent le même nombre de molécules.",
  "La stœchiométrie est l'étude quantitative des réactifs et des produits dans une réaction chimique.",
  "Les alcanes sont des hydrocarbures saturés ne contenant que des liaisons simples entre les atomes de carbone.",
  "Les ions sont des atomes ou des molécules chargés électriquement en raison d'un excès ou d'un déficit d'électrons.",
  "La thermodynamique chimique étudie les transferts d'énergie lors des réactions chimiques.",
  "Les acides forts se dissocient complètement en solution aqueuse pour produire des ions H+.",
  "La chimie analytique utilise des techniques telles que la spectroscopie et la chromatographie pour analyser la composition des échantillons.",
  "Les réactions endothermiques absorbent de la chaleur, tandis que les réactions exothermiques en libèrent.",
  "La réaction de neutralisation entre un acide et une base produit de l'eau et un sel.",
  "Les pieuvres ont trois cœurs et le sang bleu.",
  "Le miel ne se gâte jamais. On a retrouvé du miel comestible dans les tombes égyptiennes.",
  "Les éléphants peuvent se reconnaître dans un miroir, ce qui indique un certain degré de conscience de soi.",
  "Les yeux d'une autruche sont plus grands que son cerveau.",
  "Les papillons peuvent goûter avec leurs pieds.",
  "Les fourmis s'étirent le matin quand elles se réveillent, comme les humains.",
  "Les bananes sont des baies, mais les fraises ne le sont pas.",
  "Les dauphins ont des noms pour se reconnaître entre eux.",
  "La lune s'éloigne de la Terre d'environ 3,8 centimètres par an.",
  "Les fleurs de tournesol suivent le mouvement du soleil tout au long de la journée.",
  "Les éclairs peuvent produire de l'ozone, ce qui donne à l'air son odeur caractéristique après un orage.",
  "Les pingouins ont des glandes spéciales pour filtrer le sel de l'eau de mer qu'ils boivent.",
  "Le corps humain contient suffisamment de carbone pour fabriquer 9000 crayons.",
  "Les pommes flottent dans l'eau car elles sont composées à 25% d'air.",
  "Les chauves-souris sont les seuls mammifères capables de voler.",
  "L'étoile de mer n'a pas de cerveau.",
  "Les caméléons peuvent bouger chacun de leurs yeux indépendamment, leur permettant de voir dans deux directions différentes en même temps.",
  "Les girafes ont la même quantité de vertèbres cervicales que les humains (sept).",
  "Les serpents peuvent dormir pendant trois ans sans manger.",
  "Les oiseaux ne peuvent pas roter.",
  "Les kangourous ne peuvent pas reculer.",
  "Les oignons font pleurer parce qu'ils libèrent un gaz qui réagit avec les larmes pour former de l'acide sulfurique.",
  "Les araignées mangent leurs anciennes toiles pour économiser de l'énergie.",
  "Le caméléon n'attrape pas ses proies avec sa langue mais en la projetant et en la collant grâce à sa salive.",
  "Les éléphants sont les seuls animaux qui ne peuvent pas sauter."
];

// Fonction pour afficher une information aléatoire à chaque clic sur le bouton
function afficherInformation() {
  // Générer un nombre aléatoire entre 0 et la longueur de la liste des informations
  const randomIndex = Math.floor(Math.random() * infos.length);
  // Sélectionner l'élément HTML où afficher l'information
  const infoDisplay = document.getElementById("info-display");
  // Afficher l'information correspondant à l'index généré aléatoirement
  infoDisplay.textContent = infos[randomIndex];
}

// Sélectionner le bouton
const button = document.getElementById("info-button");
// Ajouter un écouteur d'événement pour détecter les clics sur le bouton
button.addEventListener("click", afficherInformation);
